### ISSUE TITLE
LV2 plugin?

### ISSUE THREAD

**Issue by mxmilkiib** [jatinchowdhury18/AnalogTapeModel#7] opened 2019-10-30 15:57 UTC
Might it be possible to get this in [LV2 plugin](https://github.com/drobilla/lv2/wiki) format, maybe via DPF or jlv2?

**Comment by jatinchowdhury18** [comment] 2019-10-30 16:48
Hello,

Unfortunately I don't have an LV2 version immediately available. This is because I've built the plugin with the JUCE framework, and JUCE doesn't currently support an LV2 exporter. If you're comfortable with this, I'd recommend trying to build with the DISTRHO version of JUCE (https://github.com/DISTRHO/juce), they claim to have an LV2 exporter. If not, I can try taking a look at it later this week.

Thanks,
Jatin

**Comment by mxmilkiib** [comment] 2020-06-28 00:01
I'm more engineer/producer than developer. What might your thought be towards using the DISTRHO JUCE fork and maybe [DPF](https://github.com/DISTRHO/DPF) itself? Various ports of projects have been made by folk like @falktx and @KottV, though there are a fair number of yours on the [list](https://github.com/mxmilkiib/carla-modular-synth-tests/wiki/WaitingForJUCE) I started collating a number of months ago :)

**Comment by KottV** [comment] 2020-06-28 05:56
AnalogTapeModel compiles fine with JUCE LV2 wrapper.

**Comment by jatinchowdhury18** [comment] 2020-06-28 20:40
@mxmilkiib Sorry I've been so quiet on this. I took a look at the DISTRHO fork, but haven't fully figured out how to compile an LV2 plugin (I wish there was some documentation on that). I contacted @falkTX, but haven't had a response yet (no worries, I'm sure he's quite busy).

@KottV: Are you referring to [this wrapper](https://github.com/DISTRHO/DISTRHO-Ports/tree/master/libs/juce/source/modules/juce_audio_plugin_client/LV2)? If so, would you mind sharing some instructions for compiling with this wrapper?

Another issue that I've had in the past is that the plugins I've compiled via the Linux machines at my school (see [here](http://ccrma.stanford.edu/planetccrma/software/planetccrma.html)) aren't always portable to other distros and architectures. Do either of you have some advice for approaching this?

My current approach for building Mac plugins (since I don't own a Mac) is to build the binaries through my Travis CI [pipeline](https://travis-ci.com/github/jatinchowdhury18/AnalogTapeModel) and then copy them into the "Bin" folder. I would love to be able to set up a similar build scheme for Linux.

**Comment by KottV** [comment] 2020-06-28 22:56
>>Are you referring to this wrapper?

It's slightly updated in my repo: https://github.com/lv2-porting-project/JUCE/tree/lv2 (I haven't made PR yet).
So at first it need that version of JUCE instead of vanilla, shouldn't break any because it just has LV2 addition.

Also some of LV2 ttl generator needed too https://github.com/lv2-porting-project/lv2-ttl-generator (I use python script). And Makefile https://github.com/lv2-porting-project/JUCE/blob/lv2/LV2.mak.in
I usually place this helper and LV2.mak (with proper _juce_target_) into plugin's root dir.
Then you have to do some to enable LV2 build:

Create JuceLibraryCode/AppConfig.h

```
// [BEGIN_USER_CODE_SECTION]
  #define JucePlugin_Build_LV2 1
  #define JucePlugin_LV2URI "https://github.com/jatinchowdhury18/AnalogTapeModel"
  #define JucePlugin_MaxNumInputChannels 2
  #define JucePlugin_MaxNumOutputChannels 2

// [END_USER_CODE_SECTION]
```

Resave project with Projucer, and include LV2.mak into Makefile:
`echo "include ../../LV2.mak" >> Builds/LinuxMakefile/Makefile`

make

In future I hope it will be more automated with cmake.

**Comment by KottV** [comment] 2020-06-28 23:06
I use openSUSE build server for this task: https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOWTapeModel
See CHOWTapeModel.spec for details.

>>Another issue that I've had in the past is that the plugins I've compiled via the Linux machines at my school (see here) aren't always portable to other distros and architectures. Do either of you have some advice for approaching this?

There may be two separate problems:
1. Forgot to set JUCE_WEB_BROWSER="0" in project. Otherwise binary will load webkit2gtk and tens of other stuff which cause problems.

2. Overall Linux distro components version difference, glibc for example. Best way is to compile binary for every common distro. Or use not bleeding edge distro for build,  openSUSE Leap 15.1 is quite old and I have reports that binary is almost works in other distros.

**Comment by KottV** [comment] 2020-06-28 23:53
Of course using the whole juce lv2 branch is not strict. If you prefer upstream tarball then there patches for it:
https://build.opensuse.org/package/show/home:kill_it:JUCE/juce

[juce-5.4.5-LV2_juce_audio_plugin_client.tar.gz](https://github.com/jatinchowdhury18/AnalogTapeModel/files/4843172/juce-5.4.5-LV2_juce_audio_plugin_client.tar.gz)
extract in modules/juce_audio_processors/format_types/
and
https://build.opensuse.org/package/view_file/home:kill_it:JUCE/juce/juce-5.4.4-LV2-audioprocessor.patch?expand=1

**Comment by mxmilkiib** [comment] 2020-06-29 00:01
@KottV what are the differences between between lv2-porting-project/JUCE and DISTRHO/juce?

**Comment by KottV** [comment] 2020-06-29 00:15
> @KottV what are the differences between between lv2-porting-project/JUCE and DISTRHO/juce?

it patched against deadlock: https://linuxmusicians.com/viewtopic.php?p=112936#p112936
and has system-wide lv2 path inludes

**Comment by jatinchowdhury18** [comment] 2020-06-29 16:21
> I use openSUSE build server for this task: https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOWTapeModel
> See CHOWTapeModel.spec for details.

@KottV, wow this is great! I wonder if maybe the simplest thing to do would be to just provide a link for Linux users to your openSUSE builds. I'd be happy to trigger new builds whenever I make a new release? I'm not totally sure how contributing works for the build server, but I'd be happy to try to add some of my other plugins as well!

@mxmilkiib for engineers/producers, do you think downloading the binaries from the openSUSE server would be an acceptable solution?

**Comment by dvzrv** [comment] 2020-06-29 16:46
@jatinchowdhury18 Hi, I package a lot of the audio things on Arch Linux.

All Linux distributions have certain criteria and rules about what is supposed to go into the official repositories. Binary blobs are  a big no-go, unless there is absolutely no way around it (e.g. for drivers/firmware).

All distributions usually build from source and in an ideal world upstreams (e.g. this project) provide all required sources (or state all required sources) to make this possible.

**Comment by mxmilkiib** [comment] 2020-06-29 18:34
@jatinchowdhury18 In the Arch context; a [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) could be made that uses such a binary with the PKGBUILD then being pushed to an [AUR](https://aur.archlinux.org/) entry with a -bin postfix, but as a user/AUR packager I prefer to make -git versions that compile from scratch. But the AUR is a "wild west" and there are no AUR helper apps in the official repos. When it comes to official binary packages managed by distro packagers, pretty much all pipelines require a tarball of the full source to build in a sandboxed (no network) environment.

**Comment by KottV** [comment] 2020-06-29 23:05
>> I'd be happy to trigger new builds whenever I make a new release?

Yes it can be done.
It's not actually a big problem but AnalogTapeModel  repo is quite large, so i decided to manually prepare tarball and exclude all except sources. For git integration OBS scm service will pull full repo.

>>I'm not totally sure how contributing works for the build server, but I'd be happy to try to add some of my other plugins as well!

Couple of them are present: https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOW https://build.opensuse.org/package/show/home:kill_it:JUCE/Bad-Circuit-Modelling

Other plugins are just matter of time:)


Another thing is that OBS can build for many different distros: Ubuntu/Debian, Arch and others (of course it requries distro-specific build files). I think about adding that but with low priority. So, if anyone wish to join or try by self - welcome.

**Comment by mxmilkiib** [comment] 2020-07-12 18:47
@KottV I'm not sure I'm understanding the OBS setup. Is it taking this repo and preparing a source tarball with code ready to "`make`" an LV2? I'm only seeing openSUSE package links though.

**Comment by KottV** [comment] 2020-07-13 00:42
@mxmilkiib
it takes plugin's codes as is and it use modified JUCE with LV2
then follows these steps https://github.com/jatinchowdhury18/AnalogTapeModel/issues/7#issuecomment-650833553

**Comment by jatinchowdhury18** [comment] 2020-07-13 20:35
Hi folks, sorry again for how slow I've been on this topic. I've got a build workflow working on the [`lv2` branch](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/lv2), if you'd like to give it a try, check out the updated [build instructions](https://github.com/jatinchowdhury18/AnalogTapeModel/blob/lv2/BUILDING.md#building-on-linux).

I've done a bit of testing, but my ability to test is somewhat limited by my Linux setup, so any additional testing would be greatly appreciated. If everything works well for you all, I'm hoping to merge this branch fairly soon!

**Comment by KottV** [comment] 2020-07-13 22:44
Awesome! I'm gonna test that asap.

One thing I'd like to notice again - is disabling webkit2gtk. It's not needed and may cause errors on gtk-based hosts. Just add JUCE_WEB_BROWSER="0" to .jucer 
also you can add JUCE_JACK="1" to ged rid of **sed -i -e 's/JUCEOPTIONS/JUCEOPTIONS JUCE_JACK="1"/'  CHOWTapeModel.jucer** dirty hack :)

**Comment by jatinchowdhury18** [comment] 2020-07-14 00:00
@KottV thank you! The issue I've found is that the plugin builds just fine without webkit2gtk, but the Projucer does not. Maybe I'll try setting `JUCE_WEB_BROWSER=0` in the Projucer as well...

I want to confirm that setting `JUCE_JACK` doesn't cause issues on Windows/MacOS, and then I can take that out :).

Thanks again for all you work on this, I definitely wouldn't have been able to get this far without it!

**Comment by KottV** [comment] 2020-07-14 00:26
Yes, Projucer requires webkit. But in CHOWTapeModel.jucer it can be switched off. In Projucer it's in Modules - juce_gui_extra - JUCE_WEB_BROWSER = "Disabled"

>>I want to confirm that setting JUCE_JACK doesn't cause issues on Windows/MacOS, and then I can take that out :).

AFAIK it uses Jack in Linux only.

**Comment by KottV** [comment] 2020-07-14 00:57
Oops, I just saw that JUCE_WEB_BROWSER is disabled in the project already. Sorry!
And I compiled plugin with your script, it seems ok)

**Comment by jatinchowdhury18** [comment] 2020-07-14 01:32
Alright, I've now disabled `JUCE_WEB_BROWSER` in the submodule fork of the Projucer, so the webkit2gtk dependency can be removed altogether. And yes, Jack is is now part of the jucer project, with no noticeable issues on Windows!

Thanks for testing! I've also added the LV2 build to the project [CI pipeline](https://travis-ci.com/github/jatinchowdhury18/AnalogTapeModel/builds/175484848), which should help make sure that future changes don't break the LV2 build.

**Comment by mxmilkiib** [comment] 2020-07-15 15:57
Thank you both so very much!

What might the possibility of tagging a release today be? It's the first 15th of the quarter so it's the #lad etc. [Quarterly Release Pact](https://libremusicproduction.com/dev/release/) day.

**Comment by jatinchowdhury18** [comment] 2020-07-16 18:26
> What might the possibility of tagging a release today be? It's the first 15th of the quarter so it's the #lad etc. Quarterly Release Pact day.

Ah, looks like I've missed it! Also, I'd prefer to only tag new releases when I've added new functionality to the plugin, which I haven't really done since the last release (though I suppose you could argue that LV2 support counts as functionality). This seems like a really cool project though, so hopefully I'll have a release for next quarter!

**Comment by mxmilkiib** [comment] 2020-07-28 23:12
I'm just getting around to packaging this for the AUR. Is there a quick way to disable the non-LV2 build targets?

**Comment by KottV** [comment] 2020-07-28 23:39
>>Is there a quick way to disable the non-LV2 build targets?

If you don't have VST2 SDK or vst-patched JUCE then LV2 and Sdandalone will build only.

**Comment by mxmilkiib** [comment] 2020-08-02 16:48
https://aur.archlinux.org/packages/chowtapemodel.lv2-git

**Comment by jatinchowdhury18** [comment] 2020-08-13 07:27
Hey all (@mxmilkiib, @KottV),

I've been making some changes today, trying improve the delay lines used in the wow/flutter processing. As part of this, I've decided to upgrade to JUCE version 6, since it has some handy delay line classes, plus some other dsp-related improvements.

With regards to the LV2 build, I've had to make a couple adjustments to the LV2 wrapper to get it to compile without errors (https://github.com/jatinchowdhury18/JUCE/commit/092ad53b4cc535edd217d8b56f2b84acb25e5add), mostly removing all references to JUCE's now-deprecated `ScopedXDisplay`.  This seems to compile with no issues, but I'm worried that the LV2 plugin window may not display. Unfortunately, I've been travelling and don't currently have access to a Linux machine for testing. If either of you have a minute to test this, that would be incredibly helpful.

To test, simply checkout the repo at [this branch](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/timing-updates), and make sure all submodules are up-to-date (i.e. `git submodule update --init`), then follow the Linux build instructions like normal (https://github.com/jatinchowdhury18/AnalogTapeModel/blob/master/BUILDING.md#building-on-linux).

Thanks,
Jatin

**Comment by KottV** [comment] 2020-08-13 13:23
Hi!

Didn't know about this plan )  
I haven't test this branch yet.

But it's better later than never to say that I updated my repo to JUCE6 https://github.com/lv2-porting-project/JUCE/tree/lv2 thanks to @osxmidi and another fresh working port from author of Camomile https://github.com/pierreguillot/Camomile/tree/dev/v1.0.7/Dependencies/juce_audio_plugin_client_LV2

Maybe you find this useful.

**Comment by falkTX** [comment] 2020-08-13 13:38
I have updated the DISTRHO-Ports JUCE to juce6, the updated LV2 version is there.
https://github.com/DISTRHO/DISTRHO-Ports/tree/master/libs/juce-current/source/modules/juce_audio_plugin_client/LV2

There is no need to do all the lv2 work yourself.
I would be glad to receive PRs for any changes that are needed.
Everyone with their own version is not good for the long-term of the wrapper.

**Comment by jatinchowdhury18** [comment] 2020-08-13 17:22
@KottV  and @falkTX,

Thanks for the comments. I probably should have checked in your repos before forging ahead with my own edits. For the moment I think I'll stick with @KottV's JUCE fork, since that's the closest to what I already have working.

Thanks both for all your hard work supporting the Linux audio community!

**Comment by KottV** [comment] 2020-08-14 02:14
>>Everyone with their own version is not good for the long-term of the wrapper.
Agree.
I made "my" fork because it work for JUCE 5.4.7.
@falkTX, can we define your repo as main for LV2 for JUCE for feature development and aim our resources to it?

**Comment by KottV** [comment] 2020-08-19 22:59
@jatinchowdhury18 
build from develop branch seems to work fine.

**Comment by KottV** [comment] 2020-09-15 10:15
>  I wonder if maybe the simplest thing to do would be to just provide a link for Linux users to your openSUSE builds. I'd be happy to trigger new builds whenever I make a new release?

Do you like to control build process in OBS? The easiest way is to make your own repository and branch my packages into it then play what you want. But actually I'm happy to trigger rebuilds when you commit to sources :)

And I'll be proud if you provide the links to my repo. I've added another your projects:

complete list:
https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOWTapeModel (vst, vst3, standalone, lv2)
https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOW (vst, standalone, lv2)
https://build.opensuse.org/package/show/home:kill_it:JUCE/Bad-Circuit-Modelling (vst, vst3, standalone)
https://build.opensuse.org/package/show/home:kill_it:JUCE/ComplexNonlinearities (vst, vst3, standalone)
https://build.opensuse.org/package/show/home:kill_it:JUCE/ChowCentaur (vst, vst3, standalone)
https://build.opensuse.org/package/show/home:kill_it:JUCE/ChowPhaser (vst, vst3, standalone)

not all with LV2 yet, but I'll do

and https://build.opensuse.org/package/show/home:kill_it:JUCE/NewMixer I hope it will get new breath

**Comment by jatinchowdhury18** [comment] 2020-09-15 16:39
@KottV,

I think for now I'll leave these repos in your hands, especially the Bad Circuit Models, and Complex Nonlinearities, since I'm not expecting to change that code very much inthe future. CHOW and the Centaur probably won't have too much activity either.

Perhaps for the Phaser and the Tape Model, I might want create my own branches like you mentioned. When I have some time I'll try to play around with it.

Unfortunately, I haven't been working much on NewMixer lately, but sure when I'll pick up again with that .. :(.

In the meantime, I'm happy to include links to your repos in the documentation for each project!

Thanks as always for your hard work in setting up these build processes, I really appreciate it!

**Comment by laex333** [comment] 2020-10-15 12:14
Hi everyone! For quite a while I am following your great project and would really love to use it on my Linux Mint 20 machine too. 

Being a noob when it comes to building software, I tried my best to build it, but I can't get it to work and I give up here. Then I tried the opensuse-build (used Alien to convert from rpm to deb), which seemed to install OK, but now I still don't find any lv2-files/folders so I am stuck here too without the plugin...

So sorry for bugging you... But if you have any more options or advice, on how to use it on Linux Mint, that would be really great! Thanks a lot!

**Comment by KottV** [comment] 2020-10-15 12:23
Hi,
openSUSE rpm installs it into /usr/lib64/lv2
you can list all of your LV2 plugins by running **lv2ls** command

**Comment by laex333** [comment] 2020-10-15 18:59
Hi @KottV, thanks a lot for your kind help!
The standalone is installed and seems to work (just did a very brief test), but there is no trace of lv2 on my Linux Mint after installing either the openSUSE Tumbleweed, nor openSUSE Leap 15.2 binary (converted to .deb with Alien). There is no /usr/lib64/ at all on my machine (my lv2 files usually are in /usr/lib/lv2/), the directory also doesn't get created during install, nor does it install the plugins there when I manually create it beforehand...
Anything else I can try? If you have any further ideas, thanks in advance for sharing them...

**Comment by KottV** [comment] 2020-10-15 22:47
the package contains these file:
/usr/lib64/lv2
/usr/lib64/lv2/CHOWTapeModel.lv2
/usr/lib64/lv2/CHOWTapeModel.lv2/CHOWTapeModel.so
/usr/lib64/lv2/CHOWTapeModel.lv2/CHOWTapeModel.ttl
/usr/lib64/lv2/CHOWTapeModel.lv2/manifest.ttl
/usr/lib64/lv2/CHOWTapeModel.lv2/presets.ttl
/usr/share/doc/packages/lv2-CHOWTapeModel
/usr/share/doc/packages/lv2-CHOWTapeModel/README.md
/usr/share/licenses/lv2-CHOWTapeModel
/usr/share/licenses/lv2-CHOWTapeModel/LICENSE

you can unpack CHOWTapeModel.lv2 dir into your home ~/.lv2 with archiver app or with MC

**Comment by laex333** [comment] 2020-10-16 08:11
@KottV, thank you so so much for your kind help!

I just learned that unpacking .rpm (or .deb) is a very simple option - how great is that! (Sorry for my inexperience.)

Finally, can you please point me to the lv2-package you mention (am I blind?): When I do "download package" from https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOWTapeModel, then chose "download binary directly" on the next page (https://software.opensuse.org//download.html?project=home%3Akill_it%3AJUCE&package=CHOWTapeModel) there is only the standalone version contained? What am I missing? See:

```
$ rpm2cpio CHOWTapeModel-2.6.0+git0.3f6967e-lp152.3.1.x86_64.rpm  | cpio -idmv
./usr/bin/CHOWTapeModel
./usr/share/doc/packages/CHOWTapeModel
./usr/share/doc/packages/CHOWTapeModel/README.md
./usr/share/licenses/CHOWTapeModel
./usr/share/licenses/CHOWTapeModel/LICENSE
```

Thank you so much!!

**Comment by KottV** [comment] 2020-10-16 08:38
https://download.opensuse.org/repositories/home:/kill_it:/JUCE/openSUSE_Leap_15.2/x86_64/
All is here

**Comment by laex333** [comment] 2020-10-16 09:03
OMG... Thank you very much!

For what it's worth: I can confirm that these lv2 binaries work on LinuxMint 20 in Ardour 6.3 straight away...

Maybe this info can be helpful to other noobs like myself... ;)

Fantastic - thank you!

**Comment by jatinchowdhury18** [comment] 2020-10-16 15:19
Glad you got it working! Thanks as always @KottV 👍

**Comment by dromer** [comment] 2021-02-02 15:10
The LV2 build totally works for me.

Please add it to the win & mac builds as well so it can be included in the zip that is provided to users.

**Comment by Biscuit-Trolley** [comment] 2021-02-24 17:09
VST3 builds of this and KlonCentaur, and VST (but not VST3) builds of the Complex Nonlinearities set appear to be working (GUIs all load and move but so far only tested KlonCentaur with actual sounds) on Ubuntu 20.04 in Reaper.
Thanks to everyone involved in sorting that, great work!

**Closed** 2021-07-28 01:24 UTC
Labels: help wanted
