### ISSUE TITLE
[BUG] Loading CHOWTapeModel from an Instrument or Audio Effect Rack on a track in Ableton Live 10 causes the DAW to crash 

### ISSUE THREAD

**Issue by kakodaemon0000** [jatinchowdhury18/AnalogTapeModel#121] opened 2021-01-08 17:19 UTC
When CHOWTapeModel is loaded on a track from an Audio Effect Rack or Instrument Rack preset, the audio engine halts and after ~5 seconds Ableton Live displays the "A serious program error has occurred." error message, closing the program when OK is pressed.

1. Load CHOWTapeModel to a MIDI or audio track from Audio Effects folder
2. Select CHOWTapeModel in the detail view and press Ctrl-G or right click and press Group to place the track in an Audio Effect Rack
3. Press the Save Preset button in the top right of the Audio Effect Rack with the chain list expanded and save the preset to User Library
4. With another MIDI or audio track selected, double click the saved Audio Effect Rack preset, this should replicate the bug

The same behavior occurs when an Instrument Rack preset with CHOWTapeModel is loaded instead of an Audio Effect Rack

**Desktop (please complete the following information):**
 - Windows 10
 - Ableton Live 10
 - 2.70
 - 64 bit

**Comment by jatinchowdhury18** [comment] 2021-01-09 19:19
Thanks for the detailed bug report! Unfortunately, I've been able to re-create the bug on my system. Could you potentially try this Audio Effect Rack preset, and let me know if it works for you:

https://drive.google.com/file/d/1YfpMQoN4Oj4G01WUnblvkOE0-FyXIay3/view?usp=sharing

Thanks,
Jatin

**Comment by kakodaemon0000** [comment] 2021-01-10 20:04
I've tried the Audio Effect Rack preset that you've posted and can confirm that it worked without causing a crash

**Comment by jatinchowdhury18** [comment] 2021-01-11 19:20
Interesting... would it be possible to share one of the saved rack presets that causes a crash on your system? (prefereably, the rack will only contain this plugin, and stock Ableton instruments/effects)

**Comment by kakodaemon0000** [comment] 2021-01-11 23:05
No problem, I just made a new audio effect rack with only the plugin in it's initialized state and saved it as a preset, still causes a crash when loaded. Here's the link:
https://we.tl/t-ugeHpOC4sK

**Comment by jatinchowdhury18** [comment] 2021-01-13 07:25
Yeah, this effect rack caused a crash on my machine as well. I tried opening the rack with ChowTape in debug mode, but the crash seemed to happen before Ableton even tried to run any of the plugin code. I contacted Ableton support and included by crash log, so I'm hoping they'll be able to get back to me with more information.

I'll be sure to update this thread as I know more!

**Comment by jatinchowdhury18** [comment] 2021-09-04 20:21
Since this appears to be a bug with how Ableton handles the plugin in an effect rack, and I haven't been able to get a response from Ableton support (tried emailing them 3 or 4 times), I'm going to close this issue for now. Please re-open it if the problem is reoccuring or is becoming a bigger issue with the usage of the plugin.

**Closed by jatinchowdhury18** 2021-09-04 20:21 UTC
Labels: bug
